### ISSUE TITLE
Verifying environments used in the paper in this codebase

### ISSUE THREAD

**Issue by amitfishy** [abaisero/asym-rlpo#2]
Hi,

I'm just trying to find all the environments in the paper. I know the two gridverse envs are in the gridverse package.

I looked at the output of `from gym import envs
print(envs.registry.all())` and I'm just trying to find all the envs used in the paper.

I was able to find these 4 which I believe are the same versions used in the paper.
```
Heaven-Hell-3 - POMDP-heavenhell_3-episodic-v0
Heaven-Hell-4 - POMDP-heavenhell_4-episodic-v0
Shopping 5    - POMDP-shopping_5-episodic-v1
Shopping 6    - POMDP-shopping_6-episodic-v1
```

However, I'm not sure about the `Car-Flag` and `Cleaner` envs. Could you please let me know where I could find them?

Thanks
Amit

**Comment by abaisero** [comment]
Hi Amit,

You got the right IDs for heaven-hell and shopping.  Car-Flag and Cleaner are implemented in the repository directly, and are not registered with gym;  this is because they originate from other papers, but the respective authors did not provide an easily accessible public implementation, so I got the implementation directly from them and permission to host them in this repo (really bad practice, but out of my hands, sadly).  To use them with this repository, you should use the strings `extra-cleaner-v0` and `extra-car-flag-v0`.

**Comment by amitfishy** [comment]
This is really helpful, thank you!
